#!/usr/bin/env node
'use strict';

const program = require('commander');
program
  .version('1.0.0')
  .description('Fetch data from ShopEx APIs and save to ETL database')
  .command('sales', 'fetch Sales list') 
program.parse(process.argv);
